// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM32fz9fzOFbEzAdg_doOP21PAj9DhB3s',
    appId: '1:194407966210:web:636d360cdce1a29b54a91b',
    messagingSenderId: '194407966210',
    projectId: 'meals-app-d98ed',
    authDomain: 'meals-app-d98ed.firebaseapp.com',
    storageBucket: 'meals-app-d98ed.firebasestorage.app',
    measurementId: 'G-XR5TEKW7PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-5VWV2aM6PQnI40R9-rq4-DlxXUa4J4',
    appId: '1:194407966210:android:b42ef688f416f35354a91b',
    messagingSenderId: '194407966210',
    projectId: 'meals-app-d98ed',
    storageBucket: 'meals-app-d98ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQO1xxeohVMKgRdogaeeKlZaWeO4BgZg',
    appId: '1:194407966210:ios:90dd8aef5612224e54a91b',
    messagingSenderId: '194407966210',
    projectId: 'meals-app-d98ed',
    storageBucket: 'meals-app-d98ed.firebasestorage.app',
    iosBundleId: 'com.example.mealsRecommendation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZQO1xxeohVMKgRdogaeeKlZaWeO4BgZg',
    appId: '1:194407966210:ios:90dd8aef5612224e54a91b',
    messagingSenderId: '194407966210',
    projectId: 'meals-app-d98ed',
    storageBucket: 'meals-app-d98ed.firebasestorage.app',
    iosBundleId: 'com.example.mealsRecommendation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM32fz9fzOFbEzAdg_doOP21PAj9DhB3s',
    appId: '1:194407966210:web:82c4ab237b78b86b54a91b',
    messagingSenderId: '194407966210',
    projectId: 'meals-app-d98ed',
    authDomain: 'meals-app-d98ed.firebaseapp.com',
    storageBucket: 'meals-app-d98ed.firebasestorage.app',
    measurementId: 'G-85GN6CTKSD',
  );
}
